### ISSUE TITLE
Did not preallocate enough memory to allocate 70068 bytes

### ISSUE THREAD

**Issue by yanwuxuv587** [github/codeql-cli-binaries#102]
I encountered this problem when using the ql of lgtm to query the java database on m1 pro. At the same time, I can use it successfully when I try it on windows. What should I do to solve such a memory error?
![image](https://user-images.githubusercontent.com/38042577/146680610-bc874593-6b59-436a-bdcd-8512786a279c.png)

**Comment by hmakholm** [comment]
This seems to happen occasionally lately; we're actively trying to figure out what causes it.

Rerunning the queries / the analysis from a fresh database will usually make it go away,

**Comment by yanwuxuv587** [comment]
As you said, re-running the query/analysis from the new database will still cause the same memory error. What I said here is only for the java database, and then I tried to roll back the codeql-cli version to 2.7.1. This error is not Will appear, the ql statement is successfully executed and the expected result is obtained.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Henning ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 晚上11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [github/codeql-cli-binaries] Did not preallocate enough memory to allocate 70068 bytes (Issue #102)






最近这似乎偶尔会发生；我们正在积极地尝试找出原因。

从一个新的数据库重新运行查询/分析通常会使它消失，

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人. 
***@***.***与&gt;

**Comment by hmakholm** [comment]
We have figured out why this happens, and a fix is on the way through the release pipeline.

Until it gets fixed, a workaround on M1-based macs will be to pass `--off-heap-ram=0` on the `codeql` command line when evaluating queries. That disables the code that triggers the bug.
