### ISSUE TITLE
Default maximum compilation cache size

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-cli-binaries#111]
All CLI commands with `--compilation-cache-size` option are documented as:
> Override the default maximum size for a compilation cache directory.

However, none of them seem to mention the actual default value, and it does not seem to be documented anywhere else. What is the default value? Or is this an implementation detail?

**Comment by edoardopirovano** [comment]
I believe this is deliberately not documented in order to encourage users who need the compilation cache to be a specific size to pass in the flag. Looking at the code, I can tell you that the default is currently set to `2^28` bytes which is around 268 megabytes, but this may change in the future.

**Comment by Marcono1234** [comment]
Thanks a lot for this information! That should be large enough for my use case. I will close this issue then if the default is deliberately not documented.
