### ISSUE TITLE
Could not detect a suitable build command for the source checkout

### ISSUE THREAD

**Issue by sreekanthgude** [github/codeql-cli-binaries#112]
I am trying to create codeQL java database in my windows machine and getting below error.
cli\codeql\java\tools\autobuild.cmd]
[2022-02-18 14:58:31] [build-stderr] ERROR: Could not detect a suitable build command for the source checkout.
[2022-02-18 14:58:31] [ERROR] Spawned process exited abnormally (code 1; tried to run

Could you please check ASAP

**Comment by RasmusWL** [comment]
Hi @sreekanthgude. Can you share some details of what project you're trying to build (and what Java buildsystem it uses), and what version of CodeQL you are using?

FYI Java autobuild is described in more detail [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-the-codeql-workflow-for-compiled-languages#java)

**Comment by Sk1y233** [comment]
I think you are missing the step to compile the entire project。
codeql database create codeql_project --language=java --command="mvn clean install --file pom.xml"

**Comment by Sk1y233** [comment]
I think you are missing the step to compile the entire project.
codeql database create codeql_project --language=java --command="mvn clean install --file pom.xml"
