### ISSUE TITLE
Referenced pack 'codeql/javascript-all' not found

### ISSUE THREAD

**Issue by ehsankhodayar** [github/codeql-cli-binaries#114]
Hi,
I have downloaded and extracted CodeQL CLI on my windows 10 successfully and I have also added the <extraction-root>/codeql to my PATH as codeql. I can also create a database for a given javascript project successfully. However, when I want to do database analysis using `codeql database analyze db_address --format=csv --output=dir/result.csv queryFile.ql`, it gives me the following error:

> Referenced pack 'codeql/javascript-all' not found

I have created a qlpack.yml file in the root of my query directory with the following contents:
`name: org-queries
dependencies:
  codeql/javascript-all: "*"`

Moreover, I have also used the `codeql pack download codeql/javascript-all` command to download the javascript library and its result (javascript-all) has been automatically saved in 

> C:\Users\USER_NAME\\.codeql\packages\codeql

 directory.

I have tried many different things but have still not been successful. Can you tell me what should I do?!

**Comment by aibaars** [comment]
Have you tried running `codeql pack install` in/on your query pack directory?

**Comment by ehsankhodayar** [comment]
> Have you tried running `codeql pack install` in/on your query pack directory?

Thank you so much. I actually tried to use it multiple times but I didn't know where is its right place to use. My problem is resolved.

**Comment by pminchan** [comment]
Please tell me the exact location of the pack. I wasted too much time on this issue.

**Comment by kxyoke** [comment]
If I'm not wrong, you should cd into the directory that contains your `qlpack.yml` file, then run `codeql pack install`. That should install the dependencies listed in the `qlpack.yml`.
