### ISSUE TITLE
Expected result pattern

### ISSUE THREAD

**Issue by ehsankhodayar** [github/codeql-cli-binaries#115]
Hi,

I have written the following query ([Exercise 2](https://codeql.github.com/docs/codeql-language-guides/analyzing-data-flow-in-javascript-and-typescript/#analyzing-data-flow-in-javascript-and-typescript)) for the NodeJS library database, named ex2.ql:

> /**
>  * @kind path-problem
>  * @problem.severity recommendation
>  * @id test123
>  */
> 
> import javascript
> 
> class HardCodedTagNameConfiguration extends DataFlow::Configuration {
>   HardCodedTagNameConfiguration() { this = "HardCodedTagNameConfiguration" }
> 
>   override predicate isSource(DataFlow::Node source) { source.asExpr() instanceof ConstantString }
> 
>   override predicate isSink(DataFlow::Node sink) {
>     sink = DataFlow::globalVarRef("document").getAMethodCall("createElement").getArgument(0)
>   }
> }
> 
> from HardCodedTagNameConfiguration cfg, DataFlow::Node source, DataFlow::Node sink
> where cfg.hasFlow(source, sink)
> select source, sink

I have also created a database for the NodeJs library manually using the following command from the NodeJs library root:

`codelql database create <databaseDir> ....`

In order to perform my query, I use the following command

`codeql database analyze C:\Users\Ehsan\Desktop\lib\database --format=csv --output=C:\Users\Ehsan\Desktop\lib\output\result.csv C:\Users\Ehsan\Desktop\lib\query\ex2.ql`

However, when I execute my query, I receive the following error:

> C:\Users\Ehsan>codeql database analyze C:\Users\Ehsan\Desktop\lib\database --format=csv --output=C:\Users\Ehsan\Desktop\lib\output\result.csv C:\Users\Ehsan\Desktop\lib\query\ex2.ql --rerun
Running queries.
Compiling query plan for C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
WARNING: A path-problem query must select an edge relation. (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:1,1-5,4)
[1/1 comp 3m13s] Compiled C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
Starting evaluation of org-queries\ex2.ql.
[1/1 eval 7.9s] Evaluation done; writing results to org-queries\ex2.bqrs.
Shutting down query evaluator.
Interpreting results.
**A fatal error occurred:** Could not process query metadata for C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
Error was: Expected result pattern(s) are not present for path-problem query: Expected at least two result patterns. These should include at least an 'edges' result set (see https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/). [INVALID_RESULT_PATTERNS]

When I want to run any other types of path queries, I receive this error. Can you help me to resolve this issue please?

**Comment by tausbn** [comment]
In order for path queries to be interpreted correctly, it is important that the query produces the necessary output. For path problems in particular, it is expected that the output contains an `edges` relation, that specifies the edges in the dataflow graph.

In order to get this relation in the output, you need to import the library that handles path problems. For JavaScript, this would be 

```ql
import DataFlow::PathGraph
```

Adding the above line to your file will activate the `edges` relation. However, you also need to ensure the `select` statement is selecting the right things. I suggest looking at some of the existing JavaScript path-problems to see what form the `select` clause should take.

**Comment by ehsankhodayar** [comment]
Thank you for your response. I imported DataFlow::PathGraph, and after that, I got the following error:

> Running queries.
> Compiling query plan for C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
> WARNING: A path-problem query must select at least 4 columns. (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:20,1-22,20)
> [1/1] Found in cache: C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
> Starting evaluation of org-queries\ex2.ql.
> [1/1 eval 5.3s] Evaluation done; writing results to org-queries\ex2.bqrs.
> Shutting down query evaluator.
> Interpreting results.
> A fatal error occurred: Could not process query metadata for C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
> Error was: Expected result pattern(s) are not present for path-problem query: Expected at least 4 columns [INVALID_RESULT_PATTERNS]

Then I added two more columns to the select code as follows:
`select source, source, sink, "message"`

Then I didn't get any error, and an empty file was generated as output:

> Running queries.
> Compiling query plan for C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
> WARNING: Node is incompatible with PathNode (the type of the edge relation). (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:22,16-22)
> WARNING: Node is incompatible with PathNode (the type of the edge relation). (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:22,24-28)
> [1/1 comp 50.6s] Compiled C:\Users\Ehsan\Desktop\lib\query\ex2.ql.
> Starting evaluation of org-queries\ex2.ql.
> [1/1 eval 7.3s] Evaluation done; writing results to org-queries\ex2.bqrs.
> Shutting down query evaluator.
> Interpreting results.

I am totally new to CodeQL, and I think the problem is from my side, but I appreciate it if you help me solve it. My query is as same as CodeQL documentation Exercise 2 for javascript path queries, so it should work well. Thanks!

**Comment by tausbn** [comment]
I note that you have two warnings in your output:
```
WARNING: Node is incompatible with PathNode (the type of the edge relation). (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:22,16-22)
WARNING: Node is incompatible with PathNode (the type of the edge relation). (C:\Users\Ehsan\Desktop\lib\query\ex2.ql:22,24-28)
```

To remove these, you should change `DataFlow::Node` to `DataFlow::PathNode` in the `from` part of your `select` clause.

Does this make any difference?

**Comment by ehsankhodayar** [comment]
Thank you for the Information. My main problem was rooted in the generated database. In CodeQL documentation, they have not well described that what are their target databases for those sample queries. So, I switched to the [LGTM](https://lgtm.com/) website and ran the following query on its available projects and got the expectable output.

```
/**
 * @kind path-problem
 * @problem.severity recommendation
 * @id test123
 */

import javascript
import DataFlow
import DataFlow::PathGraph

class CommandLineFileNameConfiguration extends TaintTracking::Configuration {
  CommandLineFileNameConfiguration() { this = "CommandLineFileNameConfiguration" }

  override predicate isSource(DataFlow::Node source) {
    DataFlow::globalVarRef("process").getAPropertyRead("argv").getAPropertyRead() = source
  }

  override predicate isSink(DataFlow::Node sink) {
    DataFlow::moduleMember("fs", "readFile").getACall().getArgument(0) = sink
  }
}

from CommandLineFileNameConfiguration cfg, PathNode source, PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "Message"
```
