### ISSUE TITLE
Run Analysis on certain files 

### ISSUE THREAD

**Issue by BobbyTRU** [github/codeql-cli-binaries#126]
I was wondering if a query can be configured to analyze only a specific file.

**Comment by aibaars** [comment]
Could you clarify what you are trying to achieve? 

In general a CodeQL query may need information from many files. For example when a dataflow query tracks flow through the program.  Other queries may look only at local properties and for those analysing a single file could make sense. 

If you want a query to "see" all the files so it can perform proper flow analysis, but want to report results only on some (or a single) files, you could use https://github.com/zbazztian/filter-sarif/ to filter the results.
