### ISSUE TITLE
CodeQL Cpp Library Errors when Publishing CodeQL Pack

### ISSUE THREAD

**Issue by lauragonzalezzz** [github/codeql-cli-binaries#148]
[Publish_WHCP22H2_CodeQLPack.txt](https://github.com/github/codeql-cli-binaries/files/10316379/Publish_WHCP22H2_CodeQLPack.txt)

Heyo! I am attempting to publish Microsoft/WHCP_22H2 CodeQL pack following directions from [Creating and working with CodeQL packs](https://codeql.github.com/docs/codeql-cli/creating-and-working-with-codeql-packs/) and [Publishing and using CodeQL packs](https://codeql.github.com/docs/codeql-cli/publishing-and-using-codeql-packs/) but it fails due to errors in the `cpp-all` library with the following message:
`A fatal error occurred: A 'codeql pack create' operation failed with error code 2`

Can you help me understand what I need to do to get my package published?
I've attached a log for your reference. Thanks!

**Comment by jketema** [comment]
Hi @lauragonzalezzz,

Looking at your log, it seems the CodeQL CLI you're trying to use is older than the `cpp-all` pack, and the `cpp-all` pack uses features that were not part of the CLI version you're using (2.6.3?). The solution is to use a CLI version that matches the one released with the `cpp-all` pack version you're trying to use. Going by the path names the you seem to be using `cpp-all` pack version 0.3.5, so the matching CLI version would be 2.10.5

**Comment by lauragonzalezzz** [comment]
Thank you for the quick response @jketema!
