### ISSUE TITLE
Linux arm64 support？

### ISSUE THREAD

**Issue by optimistic9527** [github/codeql-cli-binaries#157]

**Comment by aeisenberg** [comment]
This is a consideration for future releases. However, I can't make any promises on if or when we will release codeql support for arm. Please keep an eye on [our changelog](https://github.com/github/codeql-cli-binaries/blob/main/CHANGELOG.md) to see what each new release brings.

**Comment by optimistic9527** [comment]
> This is a consideration for future releases. However, I can't make any promises on if or when we will release codeql support for arm. Please keep an eye on [our changelog](https://github.com/github/codeql-cli-binaries/blob/main/CHANGELOG.md) to see what each new release brings.

Thanks for your answer, I'll keep an eye out
