### ISSUE TITLE
CodeQL enable breaks mono path

### ISSUE THREAD

**Issue by rmarinho** [github/codeql-cli-binaries#159]
Hi we had CodeQL enabled in our main builds without any issue, but last Friday the builds started failing with an issue related to missing mono path. This is on one of our macOS stages on the main build pipeline. 
Disabling CodeQL fixed the build. But now we are not in compliance so we need to enable it asap.  

error:

```
Could not resolve path for tool "mono" using these directories: /usr/local/microsoft/powershell/7,/Users/builder/.dotnet/tools,/Users/builder/azdo/_work/_tool/dotnet,~/Library/Developer/Xamarin/android-sdk-macosx,/Library/Frameworks/Mono.framework/Versions/Current/Commands,/usr/local/bin,/usr/local/share/dotnet,~/.dotnet/tools,/Library/Frameworks/Mono.framework/Versions/Current/Commands,/usr/bin,/bin,/usr/sbin,/sbin
/Users/builder/azdo/_work/2/s/tools/NuGet.CommandLine.5.8.1/tools/NuGet.exe is a .NET Framework executable, you might need to install Mono for it to execute successfully.
Executing: /Users/builder/azdo/_work/2/s/tools/NuGet.CommandLine.5.8.1/tools/NuGet.exe install "_NativeAssets.windows" -OutputDirectory "/Users/builder/azdo/_work/2/s/artifacts/additional-assets" -Version "0.0.0-commit.193b587552cb0ed39372a049d7e6c692db98c267.483" -ExcludeVersion -Source "[https://aka.ms/skiasharp-eap/index.json"](https://aka.ms/skiasharp-eap/index.json%22) -NonInteractive
```

build failed: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7282608&view=logs&j=501b9b04-0210-5b6f-cae8-bace5ca34eb3&t=4398fa55-45c9-5535-f123-f1f9ed93a9e1
repo : https://github.com/dotnet/maui/
pipeline: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=13330

**Comment by MathiasVP** [comment]
Hi @rmarinho,

Thanks for your issue! I've reached out to the CodeQL C# team, and I hope that they'll be able to help your with this. I'll make sure to keep you updated.

**Comment by sidshank** [comment]
Hey @rmarinho! 👋🏼 Thank you for sharing the build logs. Based on the information we see in the build logs, we've asked the Microsoft-internal CodeQL team to get in touch with you directly to help you.
