### ISSUE TITLE
"codeql test run" throws CatastrophicError when it needs to upgrade a database

### ISSUE THREAD

**Issue by franktip** [github/codeql-cli-binaries#18]
Dear CodeQL team,

I have been trying to use the “code test run” feature on a small JavaScript project, and encountered an unexpected com.semmle.util.exception.CatastrophicError exception. This is using CodeQL 2.0.2 on a MacBook Pro running OS/X 10.14.6

I would really like to use CodeQL’s testing facilities for a large JS project, so I hope you can resolve the issue quickly.

Thanks,

  -Frank Tip (f.tip@northeastern.edu)

My setup is as follows. I have two subdirectories “queryjs” and “testjs” in the same directory.

1. In directory queryjs, I have files EmptyThen.ql and qlpack.yml as follows:

-----------------------------------------------------
EmptyThen.ql:
import java

from IfStmt ifstmt
where ifstmt.getThen() instanceof EmptyStmt
select ifstmt, "This if statement has an empty then."
-----------------------------------------------------
qlpack.yml:
name: emptythenjs
version: 0.0.0
libraryPathDependencies: codeql-javascript
-----------------------------------------------------

2. in directory testjs, I have files EmptyThen.expected, EmptyThen.qlref, qlpack.yml, test.js as follows:

-----------------------------------------------------
EmptyThen.expected:
| Test.java:3:5:3:22 | stmt | This if statement has an empty then. |
-----------------------------------------------------
EmptyThen.qlref:
EmptyThen.ql
-----------------------------------------------------
qlpack.yml:
name: emptythenjs-tests
version: 0.0.0
libraryPathDependencies: emptythenjs
extractor: javascript
-----------------------------------------------------
test.js:
function problem(arg) {
    if (arg.isEmpty())
    ;
    {
        System.out.println("Empty argument");
    }
}

function good(arg) {
    if (arg.isEmpty()) {
        System.out.println("Empty argument");
    }
}
-----------------------------------------------------

3. Now when I cd into the testjs directory, and execute the following command:
 codeql test run --search-path=../queryjs EmptyThen.qlref

the following error occurs:

Executing 1 tests in 1 directories.
Extracting test database in /Users/franktip/tmp/testquery/testjs.
Upgrading database for /Users/franktip/tmp/testquery/testjs.
Could not upgrade the dataset in /Users/franktip/tmp/testquery/testjs: com.semmle.util.exception.CatastrophicError: There should be a --library-path option for com.semmle.cli2.LibraryPathOptions.libraryPath but we didn't find it.
com.semmle.util.exception.CatastrophicError: There should be a --library-path option for com.semmle.cli2.LibraryPathOptions.libraryPath but we didn't find it.
[1/1] FAILED(UPGRADE) /Users/franktip/tmp/testquery/testjs/EmptyThen.qlref
0 tests passed; 1 tests failed:
  FAILED: /Users/franktip/tmp/testquery/testjs/EmptyThen.qlref

**Comment by hmakholm** [comment]
Thanks for this bug report. It turns out there is indeed a bug in the implementation.

The bug is triggered by the fact that your checkout of the `Semmle/ql` repository is newer than the extractors shipped with the CodeQL CLI, such that the database created from the test source needs to be upgraded before the test queries can be executed. There is specific code in `codeql test run` to bridge this situation, but it turns out this code doesn't actually work.

We will fix this in the next release of the CLI, hopefully to be out within a few weeks.

In the mean time, a workaround would be to make sure to check out the `lgtm.com` branch of `Semmle/ql` rather than the master branch. Then the versions will match, and the buggy part of the test runner is not necessary.

**Comment by hmakholm** [comment]
(For internal tracking, the PR to fix this is https://git.semmle.com/Semmle/code/pull/36199).

**Comment by franktip** [comment]
Thanks. The suggested workaround seems to work for me.

**Comment by hmakholm** [comment]
Fixed in https://github.com/github/codeql-cli-binaries/releases/tag/v2.0.3
