### ISSUE TITLE
Python: modules from site-packages are not extracted

### ISSUE THREAD

**Issue by ggolawski** [github/codeql-cli-binaries#19]
When I import a built-in module (e.g. `import os`) in my `.py` file and run `codeql database create codeql_db --language=python`, the module is extracted and included in the database:

```bash
$ codeql database create codeql_db --language=python
[...]
[2020-02-14 23:39:12] [build] [INFO] [3] Extracted file /usr/lib64/python3.7/os.py in 717ms
[...]
```

But when I import a non built-in module (e.g. `import flask`), it's not extracted.

Is that correct behavior?

**Comment by tausbn** [comment]
Is `flask` installed on your machine?
(If yes, are you running `codeql` from within a virtual environment?)

**Comment by ggolawski** [comment]
Yes, it's installed.
And it doesn't matter if I run `codeql` from virtualenv or not (`flask` is installed globally and in virtualenv). The same happens for any non built-in module, `flask` was just an example.

**Comment by RasmusWL** [comment]
Closing this since we fixed this problem back in March last year (as far as I can recall).
