### ISSUE TITLE
use codeql-cli in embedded environment

### ISSUE THREAD

**Issue by hac425xxx** [github/codeql-cli-binaries#25]
When compile code for embedded environment, it often use archxxx-gnu-gcc for compile, how could we create database for these project.

I have known that fortify can use the follow method to support this scene.
```
CC="sourceanalyse xxx  archxxx-gnu-gcc"
```

how does codeql-cli do?

**Comment by hmakholm** [comment]
Our C/C++ analysis people say this _ought to_ work out of the box -- our instrumentation of the build process should recognize the `archxxx-gnu-gcc` command as a GCC variant and act accordingly.

Have you directly experienced that it _doesn't_ work?

**Comment by p0** [comment]
To be clear, we believe that just `codeql database create --language cpp /path/to/desired/database` in the root of the project might work, if it uses standard build systems like make. If not, you can specify a build command with the `--command` option. CodeQL should autodetect compilers like `archxxx-gnu-gcc`.

If this doesn't work in your setting, please reopen this issue with the logs you observe.
