### ISSUE TITLE
CLI cannot handle spaces in directory names

### ISSUE THREAD

**Issue by gbergeson** [github/codeql-cli-binaries#30]
When the CodeQL CLI is installed in a directory with spaces in the name (such as "Program Files"), it causes the command "codeql database create <database-path> --language=java" to fail with the error "Unrecognized Option: Files\CodeQL\codeql-cli\java\tools/codeql-java-agent.jar=ignore-project,java". Moving the CLI to another directory fixes the problem (though, in my case, another problem arose).

**Comment by p0** [comment]
Thanks for reporting this; we'll look into improving the situation.

**Comment by p0** [comment]
We have a fix, which will be included in the upcoming 2.1.4 release of the CodeQL CLI. At the moment, we expect it to happen next week.
