### ISSUE TITLE
codeql query compile --check-only not working as intended

### ISSUE THREAD

**Issue by tunnelshade** [github/codeql-cli-binaries#38]
### Version

```
CodeQL command-line toolchain.
Version: 2.2.3.
Copyright (C) 2019-2020 GitHub, Inc.
Unpacked in: /Users/bmachira/workspace/codeql/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.
```

### Issue

Running `codeql query compile --check-only <ql-path>` is not finding metadata warnings or query structure warnings that are generally raised by LGTM.

### Steps

- Create a ql with below query structure. It has couple of warnings, `problem` kind always needs a severity level and number of selected columns should be even.
``` sql
/**
 * @name test
 * @description test
 * @id java/test
 * @kind problem
 */

import java

from Class c
select c
```

- Compile this query with checks only.

### Expected Output

Errors or Warnings complaining of missing metadata tag and incorrect number of columns.

### Actual Output

```
codeql query compile --check-only test.ql
Done [1/1] test.ql (8 s).
```

Did I misunderstand the flag? Is there anyway using codeql cli to achieve warnings that LGTM console gives out?

**Comment by hmakholm** [comment]
It's a known problem that `codeql query compile` doesn't verify the QLDoc metadata at all, no matter which flags are given. We've got an internal issue to make this verification happen eventually -- but currently the check that LGTM does exist only in LGTM and has not been moved into the general CodeQL functionality.

What `--check-only` does is check the syntax, type and binding correctness of the QL source itself. It will then terminate successfully without doing the (often quite slow) optimization steps that would produce a compiled query that can actually be executed against a database.

**Comment by tunnelshade** [comment]
Thank you @hmakholm.
