### ISSUE TITLE
MacOS Developer can't be verified warnings

### ISSUE THREAD

**Issue by JLLeitschuh** [github/codeql-cli-binaries#4]
On first launch on MacOS Catalina I'm getting a bunch of these errors that I have to manually bypass.
Can you sign these binaries so that Apple trusts them?

![Screen Shot 2019-11-19 at 3 03 37 PM](https://user-images.githubusercontent.com/1323708/69181810-c9540b80-0add-11ea-99df-b03b7b0b89c1.png)

It happens for the following binaries:
 - `preload_tracer`
 - `libtrace.dylib`
 - `runner`
 - `unsign`

**Comment by hmakholm** [comment]
It's a known problem -- unfortunately we became aware of it so late in the development cycle that all we had time for was document a workaround, removing the "untrusted" attributes during unpacking. See the "Catalina" boxes at https://help.semmle.com/codeql/codeql-cli/procedures/get-started.html

**Comment by JLLeitschuh** [comment]
Thanks, that did indeed fix that issue for me. Still running into the issue in #3 but at least this is resolved.

**Comment by criemen** [comment]
We shipped a workaround for this issue over a year ago, so now the out-of-the-box experience does not have this warning anymore.
