### ISSUE TITLE
Feature Request: Add -f flag to codeql database create

### ISSUE THREAD

**Issue by mario-campos** [github/codeql-cli-binaries#44]
Hello.

Have you ever attempted to `codeql database create foo` but maybe you forgot or missed a flag? So you modify the command and try to run it again, but, this time, it spits out a lovely:

```shell
$ codeql database create nuxtdb -l javascript -s nuxt.js
Initializing database at /Users/mario-campos/nuxtdb.
A fatal error occurred: Refusing to create database: '/Users/mario-campos/nuxtdb' exists and is not an empty directory.
```

It would be really nice and convenient to add a `-f`, `--force` flag to be able to  override the warning:

```shell
$ codeql database create nuxtdb -f -l javascript -s nuxt.js
Initializing database at /Users/mario-campos/nuxtdb.
WARNING: '/Users/mario-campos/nuxtdb' exists and is not an empty directory; overwriting directory...
```

Thanks

**Comment by edoardopirovano** [comment]
Seems sensible, I can take a look at this next week.

**Comment by edoardopirovano** [comment]
Added! The flag is `--overwrite` and should be in CLI 2.5.7+.

**Comment by edoardopirovano** [comment]
> Added! The flag is `--overwrite` and should be in CLI 2.5.7+.

Correction: This will make it into 2.5.6 as we had to restart our release testing of that due to some issues.

**Comment by gaurav-t-sca** [comment]
Having a similar issue, but with the CodeQL Github Action. The first run works, but subsequent runs fail during the "Initialize CodeQL" step:
```
      Exit code 2 and error was:

      A fatal error occurred: Refusing to create database: '/opt/actions-runner/_work/_temp/codeql_databases/python' exists and is not an empty directory.
Please specify a different location, or use the --overwrite flag to overwrite existing CodeQL databases.
```

I tried adding steps to delete that folder with `rm -rf` and even with `find ... -delete` but the files don't seem to get deleted and the error persists. Is there a way we can use this --override flag with the Github Action? Or maybe if --override isn't specified, check the value of an environment variable or something (since those are easy to set up with github actions)? 

Thanks in advance!

**Comment by hmakholm** [comment]
@gaurav-t-sca: It is not totally clear what you're doing to get that error. The CodeQL Action doesn't support running CodeQL more than once in the same job; there are deep architectural barriers to that, which are not limited to the location of the database.

It this is _not_ what is happening here, please open an issue against https://github.com/github/codeql-action and include information about your environment (i.e. your workflow file; do you use a self-hosted runner of a GitHub-provided one; if possible a link to a failing run, etc).
