### ISSUE TITLE
codeql create database incrementally

### ISSUE THREAD

**Issue by retanoj** [github/codeql-cli-binaries#49]
Hello, is there any way I can create database of a project incrementally?

I have a project called A, and I use codeql to check and fix some problems.
Maybe I just modify one line of a file of project A, it will create a new database totally when I want to use codeql to re-check it, right?

It costs lot of time :(
I think it could be optimize.

**Comment by hmakholm** [comment]
Thanks for the feedback.

Incremental database extraction is an often repeated request, so we're definitely aware of the wish. Unfortunately, making it come true is not as easy as it might appear at first, for various technical reasons. We do have some engineers thinking on and off about how we might make it work, but we're not at a point where I can predict any timeframes.

**Comment by retanoj** [comment]
Thanks for your reply.

As you said, incremental database extraction is not easy, but important.

I don't known the implementation of codeql extractor (cause closed source). But I known "exakat", a php static code check tool. It extracts file info into graph database.
Though "exakat" also has not incrementation feature, it gives me some inspiration about this thing.
Maybe codeql could optimize middle step of extraction if it extraction process likes "exakat" does.

And another question is why codeql not support php language yet?

**Comment by hmakholm** [comment]
The selection of supported languages is to some extent a historical accident, mostly dating back to before GitHub acquired the company behind the CodeQL technology. Adding support for a new language is very engineering intensive; we're working on making it merely _quite_ engineering intensive by reusing e.g. some of the multi-language framework behind GitHub's syntax highlighting and code navigation. Without spoiling any deep strategic secrets, I can say that PHP is very high on our wishlist of languages to benefit from that work, but we're not yet at the point of making public promises about _when_. I expect a big splashy announcement will be made when it is ready. :slightly_smiling_face:

**Comment by wangrd** [comment]
Is there a way to make the database like git that save all data change nodes and combine them, so we can query it at any node?

**Comment by hmakholm** [comment]
@wangrd, that sounds like it would be a neat idea if we had a way to make it work. It would definitely be one of the directions we look into if/when we crack the basic incremental-database-creation problem.

(The basic problem here is that many of the _intermediate_ results in a CodeQL analysis are summaries of facts collected from many different parts of the input program. Figuring out exactly which parts of them we'd need to invalidate and recompute when such-and-such small part of the input changes, is a hard problem. All of the ideas for how to do that we've investigated so far end up spending so much resources on managing the delta information, that it would be simpler and faster in the end just to analyze each version of the codebase from scratch anyway).

**Comment by leighst-anchorage** [comment]
Its basically impossible to use this in a large mono-module with go. 
An enormous amount of time - many minutes - is spent just doing this 

```
...
[2024-01-05 15:02:28] [build-stderr] 2024/01/05 15:02:28 Processing package archive/zip.
[2024-01-05 15:02:28] [build-stderr] 2024/01/05 15:02:28 Extracting types for package archive/zip.
...
```

Is this expected? 

I dont understand the description of why caching intermediate results is hard, since you can determine a lot about what can _possibly_ impact what just via go deps analysis (if a package doesnt depend on another package, its intermediate results should not need to be recomputed right?)

But even if there is some reason for that - im running codeql right now against one isolated binary in a large module which is loosely coupled to the rest of the code base, and its been extracting type information for 5+ minutes?

Maybe there is some setting we need to adjust? 

Thanks!
