### ISSUE TITLE
What is the difference between codeql test and codeql database create to generate a database?

### ISSUE THREAD

**Issue by Ovi3** [github/codeql-cli-binaries#54]
Execute `codeql test run --format jsonz --additional-packs "f:\code\js\hello;d:\codeql-repo" --threads 1 "F:\code\hello\tests\hello.qlref"` to run a test. Since the test is fail, the `hello.testproj` database is generated. So I load the database into VS Code and use to debug failing tests. 

The problem is, the query run result is not complete as I expect. But when I change the database to other one that `codeql database create` generate, the result is expected.

I notice the database that `codeql test` generate is far smaller than the database that `codeql database create` generate. 
So I wonder what is the difference between `codeql test` and `codeql database create` to generate a database?  What information that the `codeql test` doesn't generate?

(codeql version is `CodeQL command-line toolchain release 2.4.4.`)

**Comment by hmakholm** [comment]
Perhaps @github/codeql-javascript can help clarify how extraction of test databases differs from full extraction?

**Comment by asgerf** [comment]
For JavaScript, `codeql database create` automatically includes all of the [externs](https://github.com/github/codeql/tree/main/javascript/externs), but they're not included in `codeql test`. Some of the tests include small parts of an externs file for this reason.

**Comment by Ovi3** [comment]
Thanks for you information. 
As I didn't save the environment to reproduce this problem, I just close this issue for now.
