### ISSUE TITLE
Performance cliff with dual socket systems (NUMA)?

### ISSUE THREAD

**Issue by Manouchehri** [github/codeql-cli-binaries#57]
I'm noticing that after around 128 threads on a dual socket AMD EPYC platform (64/128 on each CPU, 128/256 for the whole system), the C++ extractor doesn't seem to be able to take advantage of the extra cores. Ninja by itself (without CodeQL) is able to max out all 256 threads without an issue.  My only guess was maybe there's something funky going on with having two physically separate CPUs.

This isn't a blocker for my workflow, so I'll probably try not to spend too much time with premature optimization. Would be curious to hear if anyone has had experience with using >128 threads with CodeQL.

Possibly related to #39, though unlikely.

**Comment by aeisenberg** [comment]
Which commands are you seeing this for? Can you include the cli command and all options you are using? I assume you are specifying a `-j, --threads` option as well.

**Comment by Manouchehri** [comment]
I'm building with:

```
codeql database create --language=cpp --threads=256 ../project-codeql --command='ninja -C /tmp/project/out/debug -j256'
```

I think this _might_ be a tmpfs bottleneck (since files can end up on the "wrong" side), but I have not done any profiling yet.

I wasn't able to reproduce this on my older dual Xeon E5-2650 v2 system (8/16 on each CPU, 16/32 for the whole system). I'm going to close the ticket for now until it crops up on another system.
