### ISSUE TITLE
Adding version history to database?

### ISSUE THREAD

**Issue by Manouchehri** [github/codeql-cli-binaries#59]
Is it possible to manually add my own version history metadata to a cpp database? I see the Python extractor [already fetches the commit history](https://github.com/github/codeql/blob/main/python/ql/src/external/VCS.qll) somehow, but not sure about cpp. Figured it'd be easier to ask than trying to reverse engineering the closed source extractors.

https://github.com/github/codeql/blob/307bef0ec3b581d1dda55f246a79e3a8ea370245/cpp/ql/src/semmlecode.cpp.dbscheme#L207-L235

**Comment by Manouchehri** [comment]
e.g. would be nice to write queries like this: https://github.com/github/codeql/blob/main/python/ql/src/Metrics/History/HNumberOfAuthors.ql

**Comment by criemen** [comment]
Hi @Manouchehri, sorry for the late response.
Generally, you can't have the extractor emit more database tables than it already does by itself.
However, you can do one of the following:
1. Supply a CSV file that contains rows for an external predicate at query execution time via `codeql query run --external` (see the codeql help for details), and maybe search for `external` in the QL source code to find an example of this.
2. Index a CSV file at database creation time (that comes closest to what you want). For that, run first `codeql database init`, then `codeql database trace-command` (with the build command you'd usually pass to `codeql database create`), and then `codeql database index-files --lang=csv --include=path-to-file.csv`. Afterwards, you only need to run `codeql database finalize` and you're set with a database that now contains the data from your CSV file. You can access the data via the `ExternalData` class.
Everything besides the `index-files` call is just what `codeql database create` does internally.

**Comment by Manouchehri** [comment]
Thanks for the advice! Do you know of any `.csv` examples I could use as a reference? I don't see any `.csv` files at all listed in https://github.com/github/codeql.

**Comment by criemen** [comment]
This feature is clearly underdocumented.
You can use, for example, csv files that are produced by `codeql bqrs decode --format=csv --no-titles` as input (i.e. simply separate the data by commas, and lines by `\n`.

Using option 2, you'd then query the data like this:
```ql
import external.ExternalArtifact

class Result extends ExternalData {
    Result() {
        this.getDataPath().matches("%results.csv")
    }

    string getA() {
        result = getField(1)
    }

    string getB() {
        result = getField(2)
    }

}

from Result r
select r.getA(), r.getB()
```

Assuming that your CSV file has the name `results.csv`.

For option 1, you'd declare an external predicate with `external string a();` or  `external predicate b(int a, string b);` and then use that.
