### ISSUE TITLE
`codeql database create` failing due to existing database should suggest `--overwrite`

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-cli-binaries#68]
When `codeql database create` is executed but the database already exists the following error is displayed:
```
A fatal error occurred: Refusing to create database: '/workspaces/my-project/my-codeql-db' exists and is not an empty directory.
```

CodeQL CLI 2.5.6 added the `--overwrite` flag (see #44), it would be useful (especially for new users) if the above error message mentioned this flag, e.g.:
> ```diff
> A fatal error occurred: Refusing to create database: '/workspaces/my-project/my-codeql-db' exists and is not an empty directory.
> + Use --overwrite to replace the existing database directory.
> ```

### Considerations
When the user by accident mistyped the database name (and the path refers to something else, e.g. the source directory of the project) have CodeQL CLI overwrite it might cause unintended data loss (depends on `--overwrite` behavior).
Suggesting usage of `--overwrite` might make the user directly use it without checking whether they actually used the correct database name.

**Comment by hvitved** [comment]
Seems like a reasonable suggestion to me.

**Comment by edoardopirovano** [comment]
Thanks for raising this! Seems like a good idea, I've improved this error message per your suggestion and you should see the new output in either CLI version 2.5.8 or 2.5.9 depending on when the improvement gets merged.

**Comment by Marcono1234** [comment]
Thanks a lot!
