### ISSUE TITLE
Allow trailing comma for set literal expressions

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-cli-binaries#76]
Currently CodeQL's set literal expression (`[ ... ]`) does not permit a trailing comma after the last element.
However, trailing commas have several advantages, see [Trailing commas - JavaScript MDN guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) and [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas); most notably:
- It makes version control diffs cleaner
- It easily allows reordering lines without having to add or remove commas

What is your opinion on trailling commas for set literal expressions? Do you think it would make sense to allow them, and maybe even enforce them for the CodeQL styleguide?

**Comment by edoardopirovano** [comment]
That seems like a fairly resonable suggestion - I would support allowing this. The relevant part of the QL language spec ([here](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#set-literals)) would also need updating.

**Comment by edoardopirovano** [comment]
I'm working on this and aiming to get it included in the 2.6.1 release of CodeQL.

**Comment by Marcono1234** [comment]
Thanks!

Is this repository (codeql-cli-binaries) the right place to suggest changes or features for the CodeQL language?
I have two other suggestions which currently exist as GitHub discussions in the codeql repository. Should I create issues for them here instead?
(They are https://github.com/github/codeql/discussions/5348 and https://github.com/github/codeql/discussions/5573)

**Comment by edoardopirovano** [comment]
This turns out to be a bit more involved than I had initially thought as the autoformatter would also need changing to decide where trailing commas should be used (currently, if they are added they will just be removed by the autoformatter). This will need some discussion with language teams on if/where they want the trailing commas to be inserted by the autoformatter.

**Comment by edoardopirovano** [comment]
This change will be in the next release of the CodeQL CLI, i.e. 2.6.3.

**Comment by Marcono1234** [comment]
@edoardopirovano has this actually been included in 2.6.3? The LGTM Query Console and the VS Code extension show an error for this, and trying to run a Quick Query in VS Code also fails with a compilation error.

**Comment by Marcono1234** [comment]
No worries and thanks for the update!

**Comment by hmakholm** [comment]
Release 2.7.1 of the CLI, which contains this language extension, is now out.
