### ISSUE TITLE
Failure when compiler is started from a folder-mounted ISO image

### ISSUE THREAD

**Issue by CaptainFlint** [github/codeql-cli-binaries#81]
Scenario:
* OS: Windows (tested in 2012R2 and 10)
* CodeQL version 2.4.6.
* Build tools are located on an ISO image (particularly: EWDK 11).
* This ISO image is mounted into an NTFS subdirectory instead of a disk letter.
* Analyzing: KVM guest additions drivers (NetKVM in this example, but happens with any other driver).

When building the code under CodeQL control using this development environment, CodeQL fails to recognize the compiler, and in the end just reports "No source code was seen during the build". In the build-tracer.log file I can see the following info:

```
[T 05:28:29 4112] === Intercepted call to \Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe === 
[E 05:28:50 6724] CodeQL C/C++ Extractor 1.27.0-SNAPSHOT
[E 05:28:50 6724] Current directory: C:\Devel\virtio-win\kvm-guest-drivers-windows\NetKVM
[E 05:28:50 6724] Command: C:\Devel\virtio-win\codeql-home\codeql\cpp\tools\win64/extractor.exe --mimic "\Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe" @C:\Users\CaptainFlint\AppData\Local\Temp\tmpf5986a8d202b47f1900a897c607772dc.rsp
[E 05:28:50 6724] Unknown program type; exiting.
```
Notice that the path to the compiler here looks like `\Device\CdRom1\etc...`, even though it's being started using the mounted path (I mounted it into C:\WinDDK\ewdk11 and specified this path as the base EWDK path). As soon as I unmount the ISO from the NTFS subdirectory and mount it to a disk letter (Z:\ for example), the compiler intercepting starts working as designed, and the database fills up correctly.

It would be nice to have support for NTFS-mounted development environments. They are much more user-friendly than disk letters, especially when you have many build system versions to deal with.

**Comment by jbj** [comment]
Thanks for the report. Can you post the full `build-tracer.log`?

**Comment by CaptainFlint** [comment]
Here it is.
[build-tracer.log](https://github.com/github/codeql-cli-binaries/files/7135783/build-tracer.log)

**Comment by jbj** [comment]
Thanks. To give us some more information, please try running the following command from an empty directory and post the console output and the contents of the `tmp` and `compiler_mimic_cache` directories that (hopefully) get created.

```
C:\Devel\virtio-win\codeql-home\codeql\cpp\tools\win64/extractor.exe --mimic-debug --mimic "\Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe" @C:\Users\CaptainFlint\AppData\Local\Temp\tmpf5986a8d202b47f1900a897c607772dc.rsp
```

This is the command from your log but with `--mimic-debug` added _before_ `--mimic`.

**Comment by CaptainFlint** [comment]
Well, the file `tmpf5986a8d202b47f1900a897c607772dc.rsp` is no longer there, because the build system automatically deletes the temporary list files. But I have restarted codeql and fetched the new rsp file from the temp dir before it got deleted, put it back, and then ran the command you suggested with adding `--mimic-debug`. The resulting output in the console is:
```
[E 16:31:02 7872] CodeQL C/C++ Extractor 1.27.0-SNAPSHOT
[E 16:31:02 7872] Current directory: C:\Devel\virtio-win\kvm-guest-drivers-windows\NetKVM\test
[E 16:31:02 7872] Command: C:\Devel\virtio-win\codeql-home\codeql\cpp\tools\win64/extractor.exe --mimic-debug --mimic "\Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe" @C:\Users\CaptainFlint\AppData\Local\Temp\tmp8559a969f0084d04b16f9455b70d4727.rsp
[D 16:31:02 7872] Executing: \Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe
[D 16:31:02 7872] Command line: "\Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe" --version
[E 16:31:02 7872] Unknown program type; exiting.
```
No `tmp` directory appeared; a file `compiler_mimic_cache\dc47ec1c3e59` was created with the following contents:
```
program type (Mar 19 2021 21:58:20)
win10
mtime unknown
\Device\CdRom1\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe
-----
unknown

-
could not launch version process for classification purposes
```

I guess, the culprit here is the attempt to run `cl.exe --version` which apparently fails, since `\Device\CdRom1\Program Files\etc...` is an object-based path and does not exist when the OS treats it as the normal file system path. It has to be converted from the device namespace into file namespace. I can see the following possible ways of doing that:
1. Convert the device path into the mounted file system path, and run `C:\WinDDK\ewdk11\Program Files\etc...`
2. Convert `\Device\CdRom1` into the volume GUID, prepend the namespace prefix, so the path looks like: `\\.\Volume{b16c95ea-95b4-4415-b8da-cd68c0ace901}\Program Files\etc...` (the actual GUID will be different, of course)
3. Use the fact that CdRom devices have symlinks in the GLOBAL?? object namespace, so the path can be accessed as: `\\.\CdRom1\Program Files\etc...` (i.e., just remove the `\Device` part and add the `\\.\` prefix)
4. Use the GLOBALROOT symlink that goes from the GLOBAL?? namespace into the object root, so the path can be: `\\.\GLOBALROOT\Device\CdRom1\Program Files\etc...` 

Unfortunately, I'm not that much of an expert in these matters, and I'm not sure how reliable these suggestions are (particularly, I don't know if the CdRom1 symlink is always guaranteed to exist, or only in some configurations; whether these paths are available to all users, or just admins, or just the user who mounted the ISO as a virtual CD-ROM…). So it may need futher research. Besides, I'm not sure how the path ended up being `\Device\CdRom1` in the first place. Depending on what CodeQL uses to retrieve this path, it may happen to be easier to tweak that part of code, so that it returned a proper file system path from the beginning.

**Comment by jbj** [comment]
Thanks for clarifying and excuse my lack of Windows knowledge. After your last message, my understanding is that the `\Device\...` path is not something you (or your tools) ever wrote. You wrote something like `C:\WinDDK\ewdk11\Program Files\...`, and then something deep in the CodeQL tooling has likely normalized that path to become `\Device\...`.

Is that correct? If so, I agree that my team should start by finding the code we use to normalize paths on Windows and see if we can change it to avoid ever returning `\Device\...`.

**Comment by CaptainFlint** [comment]
That is correct.

What actually happens is a bit more complicated than that. It should not really matter, but just in case, here is the specifics of how the build is performed.

What I do is set the environment variable `EWDK11_DIR=C:\WinDDK\ewdk11`, and that's all. The batch build scripts do the rest. When a build is started, the build script calls the `%EWDK11_DIR%\BuildEnv\SetupBuildEnv.cmd` batch from the EWDK (which is expanded using my variable definition into `C:\WinDDK\ewdk11\BuildEnv\SetupBuildEnv.cmd`). This batch script configures the other required environment variables. After that the variables like `PATH` have additional paths, all of which point to different subdirs in `C:\WinDDK\ewdk11`. The tools used for actual building, like `msbuild.exe`, `cl.exe`, etc., are all called without specifying any path at all. Windows searches for them in the `PATH`, finds them in those EWDK11 subdirectories and launch them from there. When they are running, I can check the process path in Process Explorer, and I see normal paths starting with `C:\WinDDK\ewdk11`.

**Comment by jbj** [comment]
Thanks for helping us debug this problem. We have a fairly good idea about how to improve our handling of folder-mounted devices, but it's a change that'll potentially affect a lot of customers, so we have to allocate time for careful testing. I'm adding it to the team's backlog.

**Comment by criemen** [comment]
Hi @CaptainFlint ,
I changed an internal API call on Windows which hopefully should resolve this issue.
Would you mind testing again with 2.7.5 and see if we still are unable to detect the compiler here?
Otherwise, a log file excerpt like above would be highly appreciated.

**Comment by CaptainFlint** [comment]
Thanks, glad to hear about it!
I'll take a look and report the results. (Unfortunately, I'm very busy at the moment, so it may take some time... I hope, not too long.)

**Comment by criemen** [comment]
Closing this issue for now.
Please re-open if the problem persists, together with a `build-tracer.log` file for us to look at. Thanks!
