### ISSUE TITLE
Add `query compile` option to disable fail-fast behavior

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-cli-binaries#82]
I am using `codeql query compile --check-only` to compile multiple queries in a directory to verify that they do not contain any errors.
The problem is that `query compile` seems to fail fast as soon as a compilation error is detect in any of the files, aborting compilation of the remaining query files. And it appears there is no option to disable this behavior.

Would it be possible to add an option to allow disabling this fail-fast behavior, so that even if errors are encountered compilation continues and additionally at the end a summary of the compilation errors is given (similar to how `test run` behaves)? For my use case most queries are independent of each other, so even if one query fails to compile I would like to see whether the other queries compile without issues. Currently this requires fixing the compilation error, and then re-running compilation again.

**Comment by aeisenberg** [comment]
This is not currently possible, but we can consider adding a flag to continue compilation on error.

**Comment by aeisenberg** [comment]
We will have this implemented in the next release of the CLI. The `codeql compile query` command will take a new option `--keep-going` or `-k` that will avoid ending the process on a compile error.

**Comment by Marcono1234** [comment]
Thanks a lot!

**Comment by Marcono1234** [comment]
@aeisenberg, it looks like there is a really minor formatting issue in the error message:
> Failed: The following 1queries have errors

There is a space missing between the number "queries ...".
