### ISSUE TITLE
Could I add json files in javascript database?

### ISSUE THREAD

**Issue by greatyy** [github/codeql-cli-binaries#85]
while I run `codeql database create -l javascript  db `, the json files are not included in database. How could I solve the problem? Thanks a lot

**Comment by greatyy** [comment]
> Hi @greatyy,
> 
> I've forwarded this question to our JavaScript experts. In the meantime, could you tell us if the code is in a is a public repository so that we can reproduce the issue?

you can use it as an example: https://github.com/greatyy/test_codeql_json/tree/main. The json file won't be packed into database

**Comment by greatyy** [comment]
By the way, my codeql-cli version is 2.6.1(2.6.2, both tested), windows 10

**Comment by asgerf** [comment]
Hi @greatyy,

By default, only `package.json` and a few other specifically recognized JSON files are extracted.

For the moment you can extract all JSON files by setting the following environment variable
```
LGTM_INDEX_FILETYPES=".json:JSON"
```
For example, the command could look like this:
```bash
env LGTM_INDEX_FILETYPES=".json:JSON" codeql database create -l javascript db
```

This is a workaround while we're working on a nicer way of configuring extraction via the CLI.

**Comment by greatyy** [comment]
> Hi @greatyy,
> 
> By default, only `package.json` and a few other specifically recognized JSON files are extracted.
> 
> For the moment you can extract all JSON files by setting the following environment variable
> 
> ```
> LGTM_INDEX_FILETYPES=".json:JSON"
> ```
> 
> For example, the command could look like this:
> 
> ```shell
> env LGTM_INDEX_FILETYPES=".json:JSON" codeql database create -l javascript db
> ```
> 
> This is a workaround while we're working on a nicer way of configuring extraction via the CLI.

Thanks a lot. My problem sovled👍
