### ISSUE TITLE
Analyze database error with csharp c# bundle suite "Unhandled literal type"

### ISSUE THREAD

**Issue by duyn9uyen** [github/codeql-cli-binaries#86]
My project was built with DotNet 5.0. I am trying to scan my project locally with the CodeQL CLI.

**Machine**: Windows 10
**CodeQl CLI**: v2.6.3. https://github.com/github/codeql-cli-binaries/releases/download/v2.6.3/codeql-win64.zip

I generate the CodeQL database with this command:
`codeql database create codeql-database --language=csharp --command='dotnet build /t:rebuild'`

Then I tried to analyze the database with this:
`codeql database analyze codeql-database csharp-code-scanning.qls --format=sarif-latest --output=scan.sarif`

**I get a Unexpected C# extractor error: Unhandled literal type.**

Can someone help? verbose log file attached.
![image](https://user-images.githubusercontent.com/6518508/136438343-5d4ddd82-46e8-4c9b-8151-4ea7e3f22547.png)
[codeql-csharp-scan-log.txt](https://github.com/github/codeql-cli-binaries/files/7306346/codeql-csharp-scan-log.txt)

**Comment by adityasharad** [comment]
The relevant snippets of `scan.sarif` that correspond to the rule ID `cs/extraction-message` would also be helpful, even if you cannot share the entire file with us. That will tell us more about the source code location involved. Feel free to filter out sensitive information.

**Comment by duyn9uyen** [comment]
@adityasharad, attached is the scrubbed `scan.sarif` file. Let me know what line reference you're interested in
[scan.sarif_scrubbed.txt](https://github.com/github/codeql-cli-binaries/files/7348585/scan.sarif_scrubbed.txt)
.
