### ISSUE TITLE
Create database failed on win10, does codeql support win10 cl.exe compiler?

### ISSUE THREAD

**Issue by ionlylove57** [github/codeql-cli-binaries#90]
create a simple helloeword file and use cl.exe compile it , without codeql.exe it can build out helloworld.exe succssfully.

BUT when I use coql cli tool try to create database, it failed. my command such as 
E:\tmp>codeql database create hello_db -l cpp --command="cl /EHsc hello.cpp"
Initializing database at E:\tmp\hello_db.
Running build command: [cl, /EHsc, hello.cpp]

[2021-11-05 15:57:56] [build-stdout] hello.cpp
[2021-11-05 15:57:57] [build-stdout] Microsoft (R) Incremental Linker Version 14.29.30038.1
[2021-11-05 15:57:57] [build-stdout] Copyright (C) Microsoft Corporation.  All rights reserved.
[2021-11-05 15:57:57] [build-stdout] /out:hello.exe
[2021-11-05 15:57:57] [build-stdout] hello.obj
Finalizing database at E:\tmp\hello_db.
No source code was seen and extracted to E:\tmp\hello_db.
This can occur if the specified build commands failed to compile or process any code.
 - Confirm that there is some source code for the specified language in the project.
 - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify
   an explicit --command.
 - For other languages, the --command must specify a "clean" build which compiles
   all the source code files without reusing existing build artefacts.
--------------------------------------------------
I open the e:\tmp\hello_db\log\build-tracer.log ,and I got:

[T 15:57:56 11920] ==== Candidate to intercept: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe ====
[T 15:57:56 11920] === Intercepted call to C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe === 
[E 15:57:57 17860] CodeQL C/C++ Extractor 2.7.0
[E 15:57:57 17860] Current directory: E:\tmp
[E 15:57:57 17860] Command: E:\codeql_home\codeql\cpp\tools\win64/extractor.exe --mimic "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe" /EHsc hello.cpp
Warning: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe does not look like a compiler. If it is infact a compiler, please contact GitHub.
[E 15:57:57 17860] Not a compiler; exiting. Reason: --version stdout was:

--version stderr was:
ÓÃÓÚ x64 µÄ Microsoft (R) C/C++ ÓÅ»¯±àÒëÆ÷ 19.29.30038.1 °æ

°æÈ¨ËùÓÐ(C) Microsoft Corporation¡£±£ÁôËùÓÐÈ¨Àû¡£

cl: ÃüÁîÐÐ warning D9002 :ºöÂÔÎ´ÖªÑ¡Ïî¡°--version¡±

cl: ÃüÁîÐÐ error D8003 :È±ÉÙÔ´ÎÄ¼þÃû

process exited with code 2

2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\link.exe" /link /errorreport:prompt 

-----------------------------------------------
codeql tried to do such command "cl --version" ?? and cl.exe does NOT support "--version" argument, so it got error and failed ?

**Comment by MathiasVP** [comment]
Hi @ionlylove57,

Sorry for the delayed response. This issue somehow didn't get picked up. From this output:
```
[E 15:57:57 17860] Not a compiler; exiting. Reason: --version stdout was:

--version stderr was:
ÓÃÓÚ x64 µÄ Microsoft (R) C/C++ ÓÅ»¯±àÒëÆ÷ 19.29.30038.1 °æ

°æÈ¨ËùÓÐ(C) Microsoft Corporation¡£±£ÁôËùÓÐÈ¨Àû¡£

cl: ÃüÁîÐÐ warning D9002 :ºöÂÔÎ´ÖªÑ¡Ïî¡°--version¡±

cl: ÃüÁîÐÐ error D8003 :È±ÉÙÔ´ÎÄ¼þÃû
```
it looks like you might be running CodeQL in a non-English environment. Is that correct? To help debug this issue, could you try changing your language on Windows to English and retry creating the database?

> codeql tried to do such command "cl --version" ?? and cl.exe does NOT support "--version" argument, so it got error and failed ?

This is the expected behavior. This shouldn't prevent the database from being created :)
