### ISSUE TITLE
i can't create a java database by codeql normally ,if you hava any idea,please tell me and feel welcome!

### ISSUE THREAD

**Issue by wongxxxx** [github/codeql-cli-binaries#94]
D:\codeSrc\java>codeql database create --language=java ./java-database --command="javac javaCodeqlTest.java"
Initializing database at D:\codeSrc\java\java-database.
Running command [javac, javaCodeqlTest.java] in D:\codeSrc\java.
[2021-11-10 15:04:34] [build-stderr] javaCodeqlTest.java:2: 閿欒: 绫籘est鏄叕鍏辩殑, 搴斿湪鍚嶄负 Test.java 鐨勬枃浠朵腑澹版槑
[2021-11-10 15:04:34] [build-stderr] public class Test {
[2021-11-10 15:04:34] [build-stderr]        ^
[2021-11-10 15:04:34] [build-stderr] 1 涓敊璇?

[2021-11-10 15:04:39] [ERROR] Spawned process exited abnormally (code 1; tried to run: [C:\Users\Administrator\Desktop\codeql-home2\codeql-win64\codeql\tools\win64\tracer.exe, C:\Users\Administrator\Desktop\codeql-home2\codeql-win64\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, javac, javaCodeqlTest.java])
A fatal error occurred: Exit status 1 from command: [C:\Users\Administrator\Desktop\codeql-home2\codeql-win64\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, javac, javaCodeqlTest.java]

**Comment by tausbn** [comment]
It's not immediately obvious to me what's going wrong here. I have a few questions:

- Does the code compile normally? (To successfully create the database, `codeql` needs to compile the code.)
- What is the error message saying about line 2 of `javaCodeqlTest.java`?
- Can you share the contents of `javaCodeqlTest.java` with us?

**Comment by wongxxxx** [comment]
well,thank tausbn a lot! and i will share my problem detailly,

First,it is the content of the javaCodeqlTest.java
public class Test {
	public static void main(String[] args) {
		for (int i = 0; i < args.length; i++) {
			switch(args.length) {
			case -2:
				return;
			case -1:
				continue;
			case 0:
				System.out.println("No args");
				break;
			case 1:
			case 2:
				System.out.println("1-2 args");
				// missing break.
			case 3:
				System.out.println("3 or more args");
				// fall-through
			case 4:
				System.out.println("4 or more args");
				if (i > 1)
					break;
				// conditionally missing break.
			case 5:
				System.out.println("foo");
				// Missing break, but switch ends.
			}
		}
	}
}
I find it in this path:C:\Users\Administrator\Desktop\codeql-home\codeql-repo \java\ql\test\query-tests\Declarations\Test.java,
it is from the folder of codeql-main and i change Test,java's name to javaCodeqlTest.java,and my codeql-cli version is 2.5.4 and my codeql-main version is 1.27.0 


Second,it happen in my windows11 and i also don't understand the meaning of this mistaken code in line2.
Third,I can't to compile the java code normally,because i can't find javaCodeqlTest.class and any database in the folder of D:\codeSrc\java.

**Comment by wongxxxx** [comment]
thanks  bro, I solve it already,
1,i change the area and language to Englisg in my windows11 ,so i solve the mistake code
2,i need to change the file name and function name in the meanwhile so that it can be compile.

**Comment by tausbn** [comment]
Ah! I'm happy to hear it. Good luck with CodeQL. :slightly_smiling_face:
