### ISSUE TITLE
How to change the building architecture while create database?

### ISSUE THREAD

**Issue by trganda** [github/codeql-cli-binaries#99]
I'm using mbp 2021 with arm64 architecture. When i create a database on `nginx-1.20.0` source code with below command

```
$ ./configure --with-debug --with-cc-opt='-O0 -g'
# The output:
# checking for OS
# + Darwin 21.1.0 arm64
# checking for C compiler ... found
# + using Clang C compiler
# + clang version: 13.0.0 (clang-1300.0.29.3)
# ...
$ codeql database create path_to_nginx-1.20.0 --language=cpp --command="make" --overwrite
```

I got some issues below

```
ld: warning: ignoring file /opt/homebrew/lib/libpcre.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

It's looks like the build target changed from arm64 to x86_64 and encounter a link error. For finding the reason, I write a script

```
#!/bin/bash
./configure --with-debug --with-cc-opt='-O0 -g' 
make
```

And run
```
codeql database create path_to_nginx-1.20.0 --language=cpp --command="sh cmd.sh" --overwrite
```

The output of ./configure is
```
Running build command: [sh, cmd.sh]
[2021-12-05 13:26:02] [build-stdout] checking for OS
[2021-12-05 13:26:02] [build-stdout]  + Darwin 21.1.0 x86_64
[2021-12-05 13:26:03] [build-stdout] checking for C compiler ... found
[2021-12-05 13:26:03] [build-stdout]  + using Clang C compiler
[2021-12-05 13:26:03] [build-stdout]  + clang version: 13.0.0 (clang-1300.0.29.3)
...
```

From the output content, it's looks like `codeql` may change some environment variable of system and cause the errors I said before.

Even I have resolve this problem by rewrite some content of the `configure` file to

```bash
if test -z "$NGX_PLATFORM"; then
    echo "checking for OS"

    NGX_SYSTEM=`uname -s 2>/dev/null`
    NGX_RELEASE=`uname -r 2>/dev/null`
    # NGX_MACHINE=`uname -m 2>/dev/null`
    # modified to 
    NGX_MACHINE=arm64

    echo " + $NGX_SYSTEM $NGX_RELEASE $NGX_MACHINE"
    
    NGX_PLATFORM="$NGX_SYSTEM:$NGX_RELEASE:$NGX_MACHINE";
else
    ....
fi
```
and re-run the command
```bash
codeql database create path_to_nginx-1.20.0 --language=cpp --command="sh cmd.sh" --overwrite
```

But, is there any way to solve this problem briefly?

**Comment by RasmusWL** [comment]
I'm not 100% on top of our support for the Apple M1 CPUs, but I've asked someone that does to take a look at your problem :blush:

**Comment by trganda** [comment]
Thanks so  much. :smile:

**Comment by RasmusWL** [comment]
Thanks again for reporting this. We've noted down this issue, and are working on it, though there is no ETA.

Note that beta support for Apple Silicon was only added in [2.7.1](https://github.com/github/codeql-cli-binaries/blob/main/CHANGELOG.md#release-271-2021-11-15).

You should be able to get around this by creating the database using a normal x86 machine, or using our [codeql-action](https://github.com/github/codeql-action) with [`debug: true`](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#creating-codeql-debugging-artifacts)

**Comment by trganda** [comment]
Thanks again and looking for a future version to fix this issue.

You solution was working for me, another tempory way is creating the database with a docker ([multi-arch](https://docs.docker.com/desktop/multi-arch/#:~:text=When%20running%20an%20image%20with%20multi-architecture%20support%2C%20docker,arm32v5%2C%20arm32v6%2C%20arm32v7%2C%20arm64v8%2C%20i386%2C%20ppc64le%2C%20and%20s390x.)) containers that support x86 architecture.

**Comment by hmakholm** [comment]
M1 support has now been out for some time, so closing this.
